import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Link } from 'react-router-dom'
import { BookOpen, FileText, Download, ArrowRight, Search, Clock, Calendar, ExternalLink, X } from 'lucide-react'
import useStore from '../../store/useStore'
import toast from 'react-hot-toast'

export const RESOURCES_DATA = [
  {
    id: 'annual-report-2024',
    title: 'Annual Intelligence Report 2024',
    category: 'Reports',
    description: 'Comprehensive analysis of national predictive telemetry across smart cities, highway corridors, and flood plains.',
    date: 'Jan 15, 2026',
    readTime: '18 min read',
    image: '/images/crime_intelligence.png',
    pdfUrl: '#',
    summary: 'This landmark report documents the 23.8M daily telemetry ingestion milestone, 98.6% predictive model accuracy across 12 metropolitan hubs, and the deployment of sovereign zero-trust AI pipelines.',
  },
  {
    id: 'ai-public-safety',
    title: 'AI in Public Safety: Transforming Communities',
    category: 'Blogs',
    description: 'How proactive anomaly detection and spatial clustering are reducing municipal emergency response times to under 3 minutes.',
    date: 'Feb 02, 2026',
    readTime: '8 min read',
    image: '/images/cyber_intelligence.png',
    summary: 'An executive breakdown of multi-agency coordination between local police dispatch, ambulance fleets, and municipal traffic controllers using NPIG spatial intelligence nodes.',
  },
  {
    id: 'smart-traffic-mgmt',
    title: 'Smart Traffic Management on National Highways',
    category: 'Case Studies',
    description: 'Real-world deployment study on NH48 and Delhi-NCR expressways delivering 31% congestion reduction and instant incident routing.',
    date: 'Dec 20, 2025',
    readTime: '12 min read',
    image: '/images/traffic_intelligence.png',
    summary: 'Evaluating dynamic signal synchronization, automatic toll plaza lane reallocation, and emergency corridor green-lights during high-volume pilgrimage and holiday seasons.',
  },
  {
    id: 'climate-risk-assessment',
    title: 'Climate Risk & Flood Inundation Assessment',
    category: 'Whitepapers',
    description: 'Methodology paper detailing satellite radar altimetry integration with hydrodynamic urban basin simulation models.',
    date: 'Nov 12, 2025',
    readTime: '22 min read',
    image: '/images/climate_intelligence.png',
    summary: 'A deep mathematical exposition on predictive rainfall runoff modeling, storm drain sensor arrays, and 36-hour pre-evacuation alert routing across Mumbai and Chennai.',
  },
  {
    id: 'national-cyber-resilience',
    title: 'National Cyber Resilience & SCADA Protection',
    category: 'Whitepapers',
    description: 'Zero-day behavioral anomaly classification for power grid transmission substations and water treatment automation.',
    date: 'Jan 28, 2026',
    readTime: '15 min read',
    image: '/images/cyber_intelligence.png',
    summary: 'Defensive architecture against distributed state-actor attacks targeting critical infrastructure, utilizing hardware-isolated air-gap telemetry relays.',
  },
  {
    id: 'healthcare-epidemic-forecast',
    title: 'Predictive Epidemic Surveillance in Urban Centers',
    category: 'Case Studies',
    description: 'Syndromic surveillance networks predicting vector-borne transmission surges 14 days prior to clinical hospital admissions.',
    date: 'Oct 18, 2025',
    readTime: '10 min read',
    image: '/images/healthcare_intelligence.png',
    summary: 'How municipal health authorities in Bengaluru leverage pharmacy sales indicators and climate telemetry to preposition medication stockpiles.',
  },
]

export default function ResourcesSection({ isStandalonePage = false }) {
  const { theme } = useStore()
  const [activeTab, setActiveTab] = useState('All')
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedResource, setSelectedResource] = useState(null)

  const tabs = ['All', 'Reports', 'Case Studies', 'Blogs', 'Whitepapers']

  const filteredResources = RESOURCES_DATA.filter((r) => {
    const matchesTab = activeTab === 'All' || r.category.toLowerCase() === activeTab.toLowerCase()
    const matchesSearch = searchQuery === '' || 
      r.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
      r.description.toLowerCase().includes(searchQuery.toLowerCase())
    return matchesTab && matchesSearch
  })

  const handleDownload = (e, item) => {
    e.stopPropagation()
    const blob = new Blob([
      `NPIG EXECUTIVE DOCUMENT: ${item.title}\nCategory: ${item.category}\nDate: ${item.date}\n\nSUMMARY:\n${item.summary}\n\nGenerated by National Predictive Intelligence Grid Sovereign Platform.\nClassification: Official Use Only.`
    ], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${item.id}.txt`
    a.click()
    URL.revokeObjectURL(url)
    toast.success(`Downloaded briefing: ${item.title}`)
  }

  return (
    <section className={`relative ${isStandalonePage ? 'py-12' : 'py-24 sm:py-32'} px-4 sm:px-6 lg:px-8`}>
      <div className="max-w-7xl mx-auto">
        
        {/* ── Section Header ── */}
        <div className="text-center max-w-3xl mx-auto mb-12">
          <p className="text-xs font-bold uppercase tracking-[0.25em] text-indigo-500 mb-3">
            Knowledge & Insights Library
          </p>
          <h2 className="font-display text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight text-slate-900 dark:text-white mb-4">
            Resources
          </h2>
          <p className="text-sm sm:text-base text-slate-600 dark:text-slate-400 font-light leading-relaxed">
            Explore reports, case studies, blogs and whitepapers on AI intelligence and analytics.
          </p>
        </div>

        {/* ── Controls: Tabs & Search Bar ── */}
        <div className="flex flex-col md:flex-row items-center justify-between gap-4 mb-10">
          
          {/* Tabs */}
          <div className="flex items-center flex-wrap gap-2">
            {tabs.map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-2 rounded-xl text-xs font-semibold transition-all duration-200 ${
                  activeTab === tab
                    ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/30'
                    : theme === 'light'
                      ? 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
                      : 'bg-[#0B1020] text-slate-400 border border-white/8 hover:text-white hover:border-white/20'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>

          {/* Search Input */}
          <div className="relative w-full md:w-72">
            <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Filter resources..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="npig-input !pl-10 !py-2 !text-xs !rounded-xl"
            />
          </div>

        </div>

        {/* ── Editorial Cards Grid ── */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {filteredResources.slice(0, isStandalonePage ? 8 : 4).map((item, i) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.08, duration: 0.5 }}
              whileHover={{ y: -6 }}
              onClick={() => setSelectedResource(item)}
              className="group cursor-pointer rounded-2xl overflow-hidden border transition-all duration-300 flex flex-col justify-between"
              style={{
                backgroundColor: theme === 'light' ? '#FFFFFF' : '#0B1020',
                borderColor: theme === 'light' ? '#E5E7EB' : 'rgba(255, 255, 255, 0.08)',
                boxShadow: theme === 'light' ? '0 4px 16px rgba(0,0,0,0.04)' : '0 8px 32px rgba(0,0,0,0.4)',
              }}
            >
              {/* Thumbnail Image */}
              <div className="relative aspect-[16/10] overflow-hidden bg-slate-900">
                <img
                  src={item.image}
                  alt={item.title}
                  className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 opacity-80 group-hover:opacity-100"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-[#0B1020] via-transparent to-transparent opacity-80" />
                <span className="absolute top-3 right-3 px-2 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-wider bg-indigo-600 text-white">
                  {item.category}
                </span>
              </div>

              {/* Card Body */}
              <div className="p-5 flex-1 flex flex-col justify-between">
                <div>
                  <div className="flex items-center gap-2 text-[10px] text-slate-400 font-mono mb-2">
                    <Calendar className="w-3 h-3 text-indigo-400" />
                    <span>{item.date}</span>
                    <span>·</span>
                    <Clock className="w-3 h-3 text-indigo-400" />
                    <span>{item.readTime}</span>
                  </div>
                  <h3 className="font-display font-bold text-sm text-slate-900 dark:text-white leading-snug group-hover:text-indigo-400 transition-colors mb-2">
                    {item.title}
                  </h3>
                  <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-light line-clamp-2">
                    {item.description}
                  </p>
                </div>

                {/* Bottom Action Strip */}
                <div className="pt-4 mt-3 border-t border-slate-100 dark:border-white/5 flex items-center justify-between">
                  <span className="text-[11px] font-semibold text-indigo-500 group-hover:text-indigo-400 flex items-center gap-1">
                    Read Brief <ArrowRight className="w-3.5 h-3.5 transform group-hover:translate-x-1 transition-transform" />
                  </span>
                  <button
                    onClick={(e) => handleDownload(e, item)}
                    className="p-1.5 rounded-lg bg-white/5 hover:bg-indigo-500/20 text-slate-400 hover:text-indigo-400 transition-colors"
                    title="Download Executive Brief"
                  >
                    <Download className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* ── View All Resources CTA ── */}
        {!isStandalonePage && (
          <div className="mt-12 text-center">
            <Link
              to="/resources"
              className="inline-flex items-center gap-2 text-xs font-bold text-indigo-500 hover:text-indigo-400 hover:underline transition-all"
            >
              View All Resources <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        )}

      </div>

      {/* ── Resource Reader Modal ── */}
      <AnimatePresence>
        {selectedResource && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className={`relative w-full max-w-2xl rounded-3xl border shadow-2xl overflow-hidden ${
                theme === 'light' ? 'bg-white border-slate-200 text-slate-900' : 'bg-[#0B1020] border-white/15 text-white'
              }`}
            >
              <div className="p-6 sm:p-8 space-y-6">
                <div className="flex items-start justify-between">
                  <div>
                    <span className="px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-indigo-600 text-white">
                      {selectedResource.category}
                    </span>
                    <h2 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white mt-3">
                      {selectedResource.title}
                    </h2>
                    <p className="text-xs text-slate-400 font-mono mt-1">
                      Published: {selectedResource.date} · Estimated: {selectedResource.readTime}
                    </p>
                  </div>
                  <button
                    onClick={() => setSelectedResource(null)}
                    className="w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center text-slate-400 hover:text-white"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>

                <div className="p-5 rounded-2xl bg-white/5 border border-white/10 space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-indigo-400">Executive Summary</h4>
                  <p className="text-xs sm:text-sm text-slate-300 leading-relaxed font-light">
                    {selectedResource.summary}
                  </p>
                </div>

                <div className="flex items-center justify-end gap-3 pt-2">
                  <button
                    onClick={() => setSelectedResource(null)}
                    className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white"
                  >
                    Close
                  </button>
                  <button
                    onClick={(e) => handleDownload(e, selectedResource)}
                    className="btn-primary !px-5 !py-2.5 !rounded-xl !text-xs !font-bold flex items-center gap-2"
                  >
                    <Download className="w-4 h-4" /> Download Full Document
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </section>
  )
}
